//@baseUrl = https://full-stack-open-p3-f9zw.onrender.com
@baseUrl = http://localhost:3001

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"Ar",
    "number":"123-456789"
}

###
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"Ada Lovelace",
    "number":"39-445323523"
}


###
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"  John Snow",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John      Snow",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow    ",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"john snow",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"Joh@n Snow",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John SnowA",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{

    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"",
    "number":"123-456789"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"123 -   102947"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"qweiurg"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"111  -  22222"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":" 111-22222"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"11122222 "
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":""
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow"
}

###

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"111-222"
}