POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"  John Snow",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John      Snow",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow    ",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"john snow",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"Joh@n Snow",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John SnowA",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{

    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"   102947"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"qweiurg"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"111    2222"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":" 111-2222"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":"1112222 "
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow",
    "number":""
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow"
}