POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Snow Snow",
    "number":"123-456-789"
}

###

POST https://full-stack-open-p3-f9zw.onrender.com/api/persons
Content-Type: application/json

{
    "name":"John Aa",
    "number":"123-456-789"
}