//@baseUrl = https://full-stack-open-p3-f9zw.onrender.com
@baseUrl = http://localhost:3001

PUT {{baseUrl}}/api/persons/67c9841560502950a3a97af4
Content-Type: application/json

{
    "name":"John Snow Snow",
    "number":"567-890222"
}

###

PUT {{baseUrl}}/api/persons/67c610db
Content-Type: application/json

{
    "name":"John Snow Snow",
    "number":"567-890222"
}

###

PUT {{baseUrl}}/api/persons/67c9841560502950a3a97af4
Content-Type: application/json

{
    "name":"John Snow Snow",
    "number":""
}

###

PUT {{baseUrl}}/api/persons/67c9841560502950a3a97af4
Content-Type: application/json

{
    "name":"",
    "number":"567-890"
}

###

PUT {{baseUrl}}/api/persons/67c9841560502950a3a97af4
Content-Type: application/json

{
    "name":"Jo",
    "number":"567-890356367"
}